/**
 * SongSnap song pool.
 *
 * Every entry is looked up at runtime against the iTunes Search API to get an
 * official 30-second preview clip — no audio ships with the game. Fields:
 *   t: track title      a: artist       c: category
 *   q: optional search-term override when the canonical name confuses search
 *
 * Categories: "90s Pop", "00s Pop", "Pop Rock", "Hip Hop", "Recent Pop".
 * Wrong-answer options are drawn from the same category, so each category
 * needs a healthy pool (25+).
 */
const SONG_POOL = [
  // ─── 90s Pop ───────────────────────────────────────────────────────────
  { t: "...Baby One More Time", a: "Britney Spears", c: "90s Pop" },
  { t: "Wannabe", a: "Spice Girls", c: "90s Pop" },
  { t: "2 Become 1", a: "Spice Girls", c: "90s Pop" },
  { t: "I Want It That Way", a: "Backstreet Boys", c: "90s Pop" },
  { t: "Everybody (Backstreet's Back)", a: "Backstreet Boys", c: "90s Pop" },
  { t: "Quit Playing Games (With My Heart)", a: "Backstreet Boys", c: "90s Pop" },
  { t: "MMMBop", a: "Hanson", c: "90s Pop" },
  { t: "No Scrubs", a: "TLC", c: "90s Pop" },
  { t: "Waterfalls", a: "TLC", c: "90s Pop" },
  { t: "Genie in a Bottle", a: "Christina Aguilera", c: "90s Pop" },
  { t: "Believe", a: "Cher", c: "90s Pop" },
  { t: "My Heart Will Go On", a: "Céline Dion", c: "90s Pop", q: "Celine Dion My Heart Will Go On" },
  { t: "Torn", a: "Natalie Imbruglia", c: "90s Pop" },
  { t: "Barbie Girl", a: "Aqua", c: "90s Pop" },
  { t: "Macarena", a: "Los Del Río", c: "90s Pop", q: "Los Del Rio Macarena" },
  { t: "Say My Name", a: "Destiny's Child", c: "90s Pop" },
  { t: "Fantasy", a: "Mariah Carey", c: "90s Pop" },
  { t: "Always Be My Baby", a: "Mariah Carey", c: "90s Pop" },
  { t: "Vogue", a: "Madonna", c: "90s Pop" },
  { t: "Ray of Light", a: "Madonna", c: "90s Pop" },
  { t: "Livin' la Vida Loca", a: "Ricky Martin", c: "90s Pop" },
  { t: "Blue (Da Ba Dee)", a: "Eiffel 65", c: "90s Pop" },
  { t: "Together Again", a: "Janet Jackson", c: "90s Pop" },
  { t: "That Don't Impress Me Much", a: "Shania Twain", c: "90s Pop" },
  { t: "Man! I Feel Like a Woman!", a: "Shania Twain", c: "90s Pop" },
  { t: "You're Still the One", a: "Shania Twain", c: "90s Pop" },
  { t: "Un-Break My Heart", a: "Toni Braxton", c: "90s Pop" },
  { t: "Kiss from a Rose", a: "Seal", c: "90s Pop" },
  { t: "What Is Love", a: "Haddaway", c: "90s Pop" },
  { t: "Rhythm Is a Dancer", a: "SNAP!", c: "90s Pop" },

  // ─── 00s Pop ───────────────────────────────────────────────────────────
  { t: "Toxic", a: "Britney Spears", c: "00s Pop" },
  { t: "Oops!... I Did It Again", a: "Britney Spears", c: "00s Pop" },
  { t: "Womanizer", a: "Britney Spears", c: "00s Pop" },
  { t: "Crazy in Love", a: "Beyoncé", c: "00s Pop" },
  { t: "Irreplaceable", a: "Beyoncé", c: "00s Pop" },
  { t: "Single Ladies (Put a Ring on It)", a: "Beyoncé", c: "00s Pop" },
  { t: "Umbrella", a: "Rihanna", c: "00s Pop" },
  { t: "SOS", a: "Rihanna", c: "00s Pop" },
  { t: "Disturbia", a: "Rihanna", c: "00s Pop" },
  { t: "Hips Don't Lie", a: "Shakira", c: "00s Pop" },
  { t: "Whenever, Wherever", a: "Shakira", c: "00s Pop" },
  { t: "Beautiful", a: "Christina Aguilera", c: "00s Pop" },
  { t: "Hollaback Girl", a: "Gwen Stefani", c: "00s Pop" },
  { t: "Poker Face", a: "Lady Gaga", c: "00s Pop" },
  { t: "Just Dance", a: "Lady Gaga", c: "00s Pop" },
  { t: "I Kissed a Girl", a: "Katy Perry", c: "00s Pop" },
  { t: "Hot N Cold", a: "Katy Perry", c: "00s Pop" },
  { t: "Bye Bye Bye", a: "*NSYNC", c: "00s Pop", q: "NSYNC Bye Bye Bye" },
  { t: "It's Gonna Be Me", a: "*NSYNC", c: "00s Pop", q: "NSYNC It's Gonna Be Me" },
  { t: "Cry Me a River", a: "Justin Timberlake", c: "00s Pop" },
  { t: "SexyBack", a: "Justin Timberlake", c: "00s Pop" },
  { t: "Rock Your Body", a: "Justin Timberlake", c: "00s Pop" },
  { t: "A Thousand Miles", a: "Vanessa Carlton", c: "00s Pop" },
  { t: "Leave (Get Out)", a: "JoJo", c: "00s Pop" },
  { t: "Promiscuous", a: "Nelly Furtado", c: "00s Pop" },
  { t: "Maneater", a: "Nelly Furtado", c: "00s Pop" },
  { t: "Don't Cha", a: "The Pussycat Dolls", c: "00s Pop" },
  { t: "Since U Been Gone", a: "Kelly Clarkson", c: "00s Pop" },
  { t: "Because of You", a: "Kelly Clarkson", c: "00s Pop" },
  { t: "Unwritten", a: "Natasha Bedingfield", c: "00s Pop" },
  { t: "Bleeding Love", a: "Leona Lewis", c: "00s Pop" },

  // ─── Pop Rock ──────────────────────────────────────────────────────────
  { t: "Mr. Brightside", a: "The Killers", c: "Pop Rock" },
  { t: "Somebody Told Me", a: "The Killers", c: "Pop Rock" },
  { t: "Wonderwall", a: "Oasis", c: "Pop Rock" },
  { t: "Don't Look Back in Anger", a: "Oasis", c: "Pop Rock" },
  { t: "Iris", a: "The Goo Goo Dolls", c: "Pop Rock" },
  { t: "Semi-Charmed Life", a: "Third Eye Blind", c: "Pop Rock" },
  { t: "All Star", a: "Smash Mouth", c: "Pop Rock" },
  { t: "All the Small Things", a: "blink-182", c: "Pop Rock" },
  { t: "What's My Age Again?", a: "blink-182", c: "Pop Rock" },
  { t: "Sk8er Boi", a: "Avril Lavigne", c: "Pop Rock" },
  { t: "Complicated", a: "Avril Lavigne", c: "Pop Rock" },
  { t: "In the End", a: "Linkin Park", c: "Pop Rock" },
  { t: "Numb", a: "Linkin Park", c: "Pop Rock" },
  { t: "Holiday", a: "Green Day", c: "Pop Rock" },
  { t: "Wake Me Up When September Ends", a: "Green Day", c: "Pop Rock" },
  { t: "Basket Case", a: "Green Day", c: "Pop Rock" },
  { t: "Kryptonite", a: "3 Doors Down", c: "Pop Rock" },
  { t: "It's My Life", a: "Bon Jovi", c: "Pop Rock" },
  { t: "Bring Me to Life", a: "Evanescence", c: "Pop Rock" },
  { t: "How You Remind Me", a: "Nickelback", c: "Pop Rock" },
  { t: "The Middle", a: "Jimmy Eat World", c: "Pop Rock" },
  { t: "Sugar, We're Goin Down", a: "Fall Out Boy", c: "Pop Rock" },
  { t: "Dance, Dance", a: "Fall Out Boy", c: "Pop Rock" },
  { t: "I Write Sins Not Tragedies", a: "Panic! At the Disco", c: "Pop Rock" },
  { t: "Misery Business", a: "Paramore", c: "Pop Rock" },
  { t: "Use Somebody", a: "Kings of Leon", c: "Pop Rock" },
  { t: "Viva la Vida", a: "Coldplay", c: "Pop Rock" },
  { t: "Yellow", a: "Coldplay", c: "Pop Rock" },
  { t: "Clocks", a: "Coldplay", c: "Pop Rock" },
  { t: "1985", a: "Bowling for Soup", c: "Pop Rock" },
  { t: "Stacy's Mom", a: "Fountains of Wayne", c: "Pop Rock" },
  { t: "Drops of Jupiter", a: "Train", c: "Pop Rock" },
  { t: "Hey There Delilah", a: "Plain White T's", c: "Pop Rock" },
  { t: "Everlong", a: "Foo Fighters", c: "Pop Rock" },
  { t: "Smells Like Teen Spirit", a: "Nirvana", c: "Pop Rock" },
  { t: "Ironic", a: "Alanis Morissette", c: "Pop Rock" },

  // ─── Hip Hop ───────────────────────────────────────────────────────────
  { t: "Juicy", a: "The Notorious B.I.G.", c: "Hip Hop", q: "Notorious BIG Juicy" },
  { t: "Mo Money Mo Problems", a: "The Notorious B.I.G.", c: "Hip Hop", q: "Notorious BIG Mo Money Mo Problems" },
  { t: "California Love", a: "2Pac", c: "Hip Hop" },
  { t: "Gangsta's Paradise", a: "Coolio", c: "Hip Hop" },
  { t: "Lose Yourself", a: "Eminem", c: "Hip Hop" },
  { t: "The Real Slim Shady", a: "Eminem", c: "Hip Hop" },
  { t: "Without Me", a: "Eminem", c: "Hip Hop" },
  { t: "In Da Club", a: "50 Cent", c: "Hip Hop" },
  { t: "21 Questions", a: "50 Cent", c: "Hip Hop" },
  { t: "Hot in Herre", a: "Nelly", c: "Hip Hop" },
  { t: "Ride wit Me", a: "Nelly", c: "Hip Hop" },
  { t: "Dilemma", a: "Nelly", c: "Hip Hop" },
  { t: "Gold Digger", a: "Kanye West", c: "Hip Hop" },
  { t: "Stronger", a: "Kanye West", c: "Hip Hop" },
  { t: "Heartless", a: "Kanye West", c: "Hip Hop" },
  { t: "99 Problems", a: "JAY-Z", c: "Hip Hop" },
  { t: "Empire State of Mind", a: "JAY-Z", c: "Hip Hop" },
  { t: "Big Pimpin'", a: "JAY-Z", c: "Hip Hop" },
  { t: "Hey Ya!", a: "OutKast", c: "Hip Hop" },
  { t: "Ms. Jackson", a: "OutKast", c: "Hip Hop" },
  { t: "Get Ur Freak On", a: "Missy Elliott", c: "Hip Hop" },
  { t: "Work It", a: "Missy Elliott", c: "Hip Hop" },
  { t: "Drop It Like It's Hot", a: "Snoop Dogg", c: "Hip Hop" },
  { t: "Still D.R.E.", a: "Dr. Dre", c: "Hip Hop" },
  { t: "The Next Episode", a: "Dr. Dre", c: "Hip Hop" },
  { t: "Yeah!", a: "Usher", c: "Hip Hop" },
  { t: "Low", a: "Flo Rida", c: "Hip Hop" },
  { t: "Crank That (Soulja Boy)", a: "Soulja Boy", c: "Hip Hop" },
  { t: "Lollipop", a: "Lil Wayne", c: "Hip Hop" },
  { t: "A Milli", a: "Lil Wayne", c: "Hip Hop" },
  { t: "Live Your Life", a: "T.I.", c: "Hip Hop" },
  { t: "Whatever You Like", a: "T.I.", c: "Hip Hop" },
  { t: "HUMBLE.", a: "Kendrick Lamar", c: "Hip Hop" },
  { t: "Alright", a: "Kendrick Lamar", c: "Hip Hop" },
  { t: "SICKO MODE", a: "Travis Scott", c: "Hip Hop" },
  { t: "God's Plan", a: "Drake", c: "Hip Hop" },
  { t: "Hotline Bling", a: "Drake", c: "Hip Hop" },
  { t: "Old Town Road", a: "Lil Nas X", c: "Hip Hop" },
  { t: "Sunflower", a: "Post Malone", c: "Hip Hop", q: "Post Malone Swae Lee Sunflower" },
  { t: "rockstar", a: "Post Malone", c: "Hip Hop", q: "Post Malone rockstar 21 Savage" },
  { t: "Congratulations", a: "Post Malone", c: "Hip Hop" },
  { t: "Mask Off", a: "Future", c: "Hip Hop" },
  { t: "Bad and Boujee", a: "Migos", c: "Hip Hop" },

  // ─── Recent Pop ────────────────────────────────────────────────────────
  { t: "Blinding Lights", a: "The Weeknd", c: "Recent Pop" },
  { t: "Save Your Tears", a: "The Weeknd", c: "Recent Pop" },
  { t: "Starboy", a: "The Weeknd", c: "Recent Pop" },
  { t: "Shape of You", a: "Ed Sheeran", c: "Recent Pop" },
  { t: "Perfect", a: "Ed Sheeran", c: "Recent Pop" },
  { t: "Thinking Out Loud", a: "Ed Sheeran", c: "Recent Pop" },
  { t: "Uptown Funk", a: "Mark Ronson", c: "Recent Pop", q: "Mark Ronson Bruno Mars Uptown Funk" },
  { t: "24K Magic", a: "Bruno Mars", c: "Recent Pop" },
  { t: "That's What I Like", a: "Bruno Mars", c: "Recent Pop" },
  { t: "Levitating", a: "Dua Lipa", c: "Recent Pop" },
  { t: "Don't Start Now", a: "Dua Lipa", c: "Recent Pop" },
  { t: "New Rules", a: "Dua Lipa", c: "Recent Pop" },
  { t: "drivers license", a: "Olivia Rodrigo", c: "Recent Pop" },
  { t: "good 4 u", a: "Olivia Rodrigo", c: "Recent Pop" },
  { t: "vampire", a: "Olivia Rodrigo", c: "Recent Pop" },
  { t: "Flowers", a: "Miley Cyrus", c: "Recent Pop" },
  { t: "Wrecking Ball", a: "Miley Cyrus", c: "Recent Pop" },
  { t: "As It Was", a: "Harry Styles", c: "Recent Pop" },
  { t: "Watermelon Sugar", a: "Harry Styles", c: "Recent Pop" },
  { t: "Anti-Hero", a: "Taylor Swift", c: "Recent Pop" },
  { t: "Shake It Off", a: "Taylor Swift", c: "Recent Pop" },
  { t: "Blank Space", a: "Taylor Swift", c: "Recent Pop" },
  { t: "Cruel Summer", a: "Taylor Swift", c: "Recent Pop" },
  { t: "bad guy", a: "Billie Eilish", c: "Recent Pop" },
  { t: "BIRDS OF A FEATHER", a: "Billie Eilish", c: "Recent Pop" },
  { t: "Stay", a: "The Kid LAROI", c: "Recent Pop", q: "The Kid LAROI Justin Bieber Stay" },
  { t: "Peaches", a: "Justin Bieber", c: "Recent Pop", q: "Justin Bieber Peaches Daniel Caesar" },
  { t: "Sorry", a: "Justin Bieber", c: "Recent Pop" },
  { t: "Love Yourself", a: "Justin Bieber", c: "Recent Pop" },
  { t: "Can't Stop the Feeling!", a: "Justin Timberlake", c: "Recent Pop" },
  { t: "Havana", a: "Camila Cabello", c: "Recent Pop", q: "Camila Cabello Havana Young Thug" },
  { t: "Señorita", a: "Shawn Mendes", c: "Recent Pop", q: "Shawn Mendes Camila Cabello Senorita" },
  { t: "Espresso", a: "Sabrina Carpenter", c: "Recent Pop" },
  { t: "Please Please Please", a: "Sabrina Carpenter", c: "Recent Pop" },
  { t: "greedy", a: "Tate McRae", c: "Recent Pop" },
  { t: "About Damn Time", a: "Lizzo", c: "Recent Pop" },
  { t: "Truth Hurts", a: "Lizzo", c: "Recent Pop" },
  { t: "Dance Monkey", a: "Tones And I", c: "Recent Pop" },
  { t: "Someone You Loved", a: "Lewis Capaldi", c: "Recent Pop" },
  { t: "Roar", a: "Katy Perry", c: "Recent Pop" },
  { t: "Firework", a: "Katy Perry", c: "Recent Pop" },
  { t: "Say So", a: "Doja Cat", c: "Recent Pop" },
  { t: "Paint The Town Red", a: "Doja Cat", c: "Recent Pop" },
  { t: "Die With A Smile", a: "Lady Gaga", c: "Recent Pop", q: "Lady Gaga Bruno Mars Die With A Smile" },
];
