/**
 * Active NBA Player Database — CAREER edition.
 *
 * The game evaluates each player's *whole career* as if they start over as a
 * rookie and play a normalized 15-season arc. So ratings here describe a
 * player's CAREER-PEAK ability (LeBron's prime, not age 41), and a set of
 * career attributes describe how that career plays out: when they peak, how
 * gracefully they age, how durable they are, whether they win, whether they
 * make teammates better, and whether they fit a team and a coach.
 *
 * Fields:
 *   id, name, age (current age — for flavor only), pos, eligible
 *
 *   ratings (0-100) — CAREER-PEAK skill profile:
 *     scoring, shooting, playmaking, rebounding,
 *     perimeterD, interiorD, athleticism, iq
 *
 *   injuryRisk (0-100) — career durability discount (history + body type).
 *
 *   career:
 *     earlyImpact   (0-100) how good they are right out of the gate
 *     aging         (0-100) how well the game ages / late-career longevity
 *     winning       (0-100) playoff performance + winning pedigree/clutch
 *     elevates      (0-100) makes teammates better & teams win
 *     ballDominance (0-100) needs the ball (high = harder to pair with alphas)
 *     culture       (0-100) locker-room/character (low = team cancer)
 *     coachability  (0-100) works within systems & with coaches
 *
 *   archetype — short label
 *
 * Ratings are subjective approximations for a draft game, not scouting truth.
 */

const PLAYER_POOL = [
  // ---------------------------------------------------------------- POINT GUARDS
  { id: "sga", name: "Shai Gilgeous-Alexander", age: 27, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 96, shooting: 84, playmaking: 88, rebounding: 60, perimeterD: 86, interiorD: 55, athleticism: 90, iq: 95 },
    injuryRisk: 22, career: { earlyImpact: 50, aging: 82, winning: 85, elevates: 78, ballDominance: 85, culture: 88, coachability: 88 },
    archetype: "Two-way lead guard" },
  { id: "luka", name: "Luka Dončić", age: 27, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 96, shooting: 85, playmaking: 96, rebounding: 78, perimeterD: 60, interiorD: 50, athleticism: 72, iq: 96 },
    injuryRisk: 48, career: { earlyImpact: 88, aging: 72, winning: 74, elevates: 84, ballDominance: 95, culture: 70, coachability: 64 },
    archetype: "Offensive engine" },
  { id: "curry", name: "Stephen Curry", age: 37, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 94, shooting: 99, playmaking: 90, rebounding: 55, perimeterD: 70, interiorD: 40, athleticism: 78, iq: 96 },
    injuryRisk: 38, career: { earlyImpact: 45, aging: 95, winning: 96, elevates: 92, ballDominance: 60, culture: 98, coachability: 95 },
    archetype: "Gravity shooter" },
  { id: "halliburton", name: "Tyrese Haliburton", age: 25, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 82, shooting: 86, playmaking: 95, rebounding: 55, perimeterD: 70, interiorD: 42, athleticism: 80, iq: 92 },
    injuryRisk: 45, career: { earlyImpact: 65, aging: 85, winning: 78, elevates: 92, ballDominance: 70, culture: 90, coachability: 88 },
    archetype: "Pace-and-space maestro" },
  { id: "brunson", name: "Jalen Brunson", age: 29, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 90, shooting: 82, playmaking: 85, rebounding: 52, perimeterD: 64, interiorD: 45, athleticism: 66, iq: 92 },
    injuryRisk: 30, career: { earlyImpact: 45, aging: 78, winning: 82, elevates: 80, ballDominance: 80, culture: 92, coachability: 90 },
    archetype: "Crafty bucket-getter" },
  { id: "cade", name: "Cade Cunningham", age: 24, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 87, shooting: 78, playmaking: 90, rebounding: 68, perimeterD: 72, interiorD: 48, athleticism: 78, iq: 88 },
    injuryRisk: 38, career: { earlyImpact: 60, aging: 80, winning: 65, elevates: 84, ballDominance: 82, culture: 85, coachability: 85 },
    archetype: "Jumbo creator" },
  { id: "lamelo", name: "LaMelo Ball", age: 24, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 86, shooting: 80, playmaking: 92, rebounding: 62, perimeterD: 56, interiorD: 38, athleticism: 84, iq: 84 },
    injuryRisk: 62, career: { earlyImpact: 70, aging: 68, winning: 50, elevates: 80, ballDominance: 88, culture: 75, coachability: 75 },
    archetype: "High-wire playmaker" },
  { id: "maxey", name: "Tyrese Maxey", age: 25, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 88, shooting: 84, playmaking: 80, rebounding: 50, perimeterD: 68, interiorD: 40, athleticism: 90, iq: 84 },
    injuryRisk: 28, career: { earlyImpact: 55, aging: 78, winning: 70, elevates: 76, ballDominance: 72, culture: 92, coachability: 90 },
    archetype: "Downhill speedster" },
  { id: "fox", name: "De'Aaron Fox", age: 28, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 88, shooting: 76, playmaking: 84, rebounding: 52, perimeterD: 74, interiorD: 44, athleticism: 96, iq: 84 },
    injuryRisk: 30, career: { earlyImpact: 55, aging: 62, winning: 68, elevates: 76, ballDominance: 82, culture: 85, coachability: 84 },
    archetype: "Blur in transition" },
  { id: "trae", name: "Trae Young", age: 27, pos: "PG", eligible: ["PG"],
    ratings: { scoring: 86, shooting: 84, playmaking: 95, rebounding: 50, perimeterD: 40, interiorD: 30, athleticism: 66, iq: 88 },
    injuryRisk: 32, career: { earlyImpact: 72, aging: 72, winning: 58, elevates: 82, ballDominance: 92, culture: 70, coachability: 70 },
    archetype: "Pick-and-roll savant" },
  { id: "garland", name: "Darius Garland", age: 26, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 82, shooting: 82, playmaking: 86, rebounding: 46, perimeterD: 58, interiorD: 34, athleticism: 74, iq: 84 },
    injuryRisk: 40, career: { earlyImpact: 50, aging: 75, winning: 60, elevates: 80, ballDominance: 78, culture: 85, coachability: 85 },
    archetype: "Shifty floor general" },
  { id: "murray", name: "Jamal Murray", age: 28, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 84, shooting: 82, playmaking: 80, rebounding: 54, perimeterD: 64, interiorD: 40, athleticism: 76, iq: 86 },
    injuryRisk: 52, career: { earlyImpact: 55, aging: 72, winning: 92, elevates: 78, ballDominance: 72, culture: 85, coachability: 85 },
    archetype: "Big-game shotmaker" },
  { id: "dlillard", name: "Damian Lillard", age: 35, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 92, shooting: 92, playmaking: 86, rebounding: 50, perimeterD: 52, interiorD: 34, athleticism: 76, iq: 90 },
    injuryRisk: 50, career: { earlyImpact: 70, aging: 78, winning: 70, elevates: 80, ballDominance: 85, culture: 90, coachability: 85 },
    archetype: "Logo-range closer" },
  { id: "ddaniels", name: "Dyson Daniels", age: 23, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 68, shooting: 66, playmaking: 76, rebounding: 64, perimeterD: 94, interiorD: 52, athleticism: 84, iq: 82 },
    injuryRisk: 26, career: { earlyImpact: 45, aging: 80, winning: 62, elevates: 78, ballDominance: 45, culture: 88, coachability: 88 },
    archetype: "Point-of-attack menace" },
  { id: "cp3", name: "Chris Paul", age: 40, pos: "PG", eligible: ["PG"],
    ratings: { scoring: 80, shooting: 80, playmaking: 98, rebounding: 50, perimeterD: 88, interiorD: 40, athleticism: 78, iq: 99 },
    injuryRisk: 58, career: { earlyImpact: 75, aging: 90, winning: 70, elevates: 96, ballDominance: 80, culture: 78, coachability: 88 },
    archetype: "Point god" },
  { id: "westbrook", name: "Russell Westbrook", age: 37, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 88, shooting: 60, playmaking: 90, rebounding: 78, perimeterD: 70, interiorD: 42, athleticism: 97, iq: 72 },
    injuryRisk: 35, career: { earlyImpact: 70, aging: 40, winning: 55, elevates: 60, ballDominance: 95, culture: 60, coachability: 55 },
    archetype: "Triple-double dynamo" },
  { id: "kyrie", name: "Kyrie Irving", age: 33, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 92, shooting: 90, playmaking: 84, rebounding: 48, perimeterD: 60, interiorD: 36, athleticism: 84, iq: 86 },
    injuryRisk: 58, career: { earlyImpact: 72, aging: 80, winning: 80, elevates: 72, ballDominance: 85, culture: 35, coachability: 45 },
    archetype: "Handles wizard" },

  // ---------------------------------------------------------------- SHOOTING GUARDS
  { id: "edwards", name: "Anthony Edwards", age: 24, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 93, shooting: 84, playmaking: 76, rebounding: 62, perimeterD: 82, interiorD: 52, athleticism: 97, iq: 82 },
    injuryRisk: 22, career: { earlyImpact: 65, aging: 80, winning: 78, elevates: 76, ballDominance: 82, culture: 85, coachability: 84 },
    archetype: "Explosive two-way wing" },
  { id: "booker", name: "Devin Booker", age: 29, pos: "SG", eligible: ["SG", "PG", "SF"],
    ratings: { scoring: 91, shooting: 88, playmaking: 82, rebounding: 52, perimeterD: 66, interiorD: 42, athleticism: 76, iq: 88 },
    injuryRisk: 30, career: { earlyImpact: 60, aging: 82, winning: 75, elevates: 80, ballDominance: 82, culture: 85, coachability: 85 },
    archetype: "Three-level scorer" },
  { id: "mitchell", name: "Donovan Mitchell", age: 29, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 90, shooting: 84, playmaking: 76, rebounding: 54, perimeterD: 70, interiorD: 44, athleticism: 88, iq: 84 },
    injuryRisk: 38, career: { earlyImpact: 70, aging: 76, winning: 72, elevates: 74, ballDominance: 82, culture: 85, coachability: 82 },
    archetype: "Microwave scorer" },
  { id: "jbrown", name: "Jaylen Brown", age: 29, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 86, shooting: 78, playmaking: 64, rebounding: 60, perimeterD: 84, interiorD: 52, athleticism: 92, iq: 78 },
    injuryRisk: 34, career: { earlyImpact: 55, aging: 76, winning: 88, elevates: 70, ballDominance: 75, culture: 82, coachability: 80 },
    archetype: "Athletic two-way wing" },
  { id: "klay", name: "Klay Thompson", age: 35, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 84, shooting: 95, playmaking: 50, rebounding: 48, perimeterD: 88, interiorD: 46, athleticism: 78, iq: 82 },
    injuryRisk: 65, career: { earlyImpact: 60, aging: 70, winning: 95, elevates: 78, ballDominance: 22, culture: 95, coachability: 95 },
    archetype: "Splash sniper / 3-and-D" },
  { id: "harden", name: "James Harden", age: 36, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 95, shooting: 86, playmaking: 92, rebounding: 60, perimeterD: 45, interiorD: 38, athleticism: 80, iq: 90 },
    injuryRisk: 42, career: { earlyImpact: 55, aging: 75, winning: 52, elevates: 82, ballDominance: 95, culture: 45, coachability: 50 },
    archetype: "Iso scoring engine" },
  { id: "bane", name: "Desmond Bane", age: 27, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 82, shooting: 88, playmaking: 74, rebounding: 60, perimeterD: 74, interiorD: 46, athleticism: 74, iq: 86 },
    injuryRisk: 30, career: { earlyImpact: 50, aging: 80, winning: 68, elevates: 78, ballDominance: 60, culture: 88, coachability: 88 },
    archetype: "Bully-ball sniper" },
  { id: "reaves", name: "Austin Reaves", age: 27, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 80, shooting: 82, playmaking: 80, rebounding: 52, perimeterD: 62, interiorD: 38, athleticism: 66, iq: 86 },
    injuryRisk: 24, career: { earlyImpact: 45, aging: 78, winning: 72, elevates: 82, ballDominance: 60, culture: 90, coachability: 90 },
    archetype: "Connective scorer" },
  { id: "dwhite", name: "Derrick White", age: 31, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 76, shooting: 82, playmaking: 78, rebounding: 56, perimeterD: 86, interiorD: 60, athleticism: 78, iq: 90 },
    injuryRisk: 22, career: { earlyImpact: 40, aging: 80, winning: 90, elevates: 84, ballDominance: 45, culture: 92, coachability: 92 },
    archetype: "Two-way glue guard" },
  { id: "lavine", name: "Zach LaVine", age: 30, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 87, shooting: 86, playmaking: 68, rebounding: 50, perimeterD: 56, interiorD: 38, athleticism: 90, iq: 74 },
    injuryRisk: 50, career: { earlyImpact: 55, aging: 70, winning: 45, elevates: 62, ballDominance: 78, culture: 72, coachability: 75 },
    archetype: "High-flying scorer" },
  { id: "herro", name: "Tyler Herro", age: 26, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 84, shooting: 86, playmaking: 74, rebounding: 54, perimeterD: 52, interiorD: 34, athleticism: 70, iq: 80 },
    injuryRisk: 40, career: { earlyImpact: 55, aging: 75, winning: 65, elevates: 68, ballDominance: 78, culture: 78, coachability: 80 },
    archetype: "Shot-making guard" },
  { id: "mcollum", name: "CJ McCollum", age: 34, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 84, shooting: 84, playmaking: 72, rebounding: 48, perimeterD: 52, interiorD: 34, athleticism: 70, iq: 86 },
    injuryRisk: 44, career: { earlyImpact: 50, aging: 76, winning: 60, elevates: 74, ballDominance: 72, culture: 90, coachability: 88 },
    archetype: "Veteran shotmaker" },

  // ---------------------------------------------------------------- SMALL FORWARDS
  { id: "tatum", name: "Jayson Tatum", age: 27, pos: "SF", eligible: ["SF", "PF", "SG"],
    ratings: { scoring: 93, shooting: 86, playmaking: 80, rebounding: 74, perimeterD: 82, interiorD: 58, athleticism: 86, iq: 88 },
    injuryRisk: 48, career: { earlyImpact: 70, aging: 82, winning: 88, elevates: 80, ballDominance: 80, culture: 88, coachability: 88 },
    archetype: "Two-way franchise wing" },
  { id: "durant", name: "Kevin Durant", age: 37, pos: "SF", eligible: ["SF", "PF"],
    ratings: { scoring: 97, shooting: 92, playmaking: 78, rebounding: 70, perimeterD: 78, interiorD: 68, athleticism: 88, iq: 90 },
    injuryRisk: 58, career: { earlyImpact: 80, aging: 88, winning: 90, elevates: 82, ballDominance: 82, culture: 78, coachability: 82 },
    archetype: "Unguardable scorer" },
  { id: "lebron", name: "LeBron James", age: 41, pos: "SF", eligible: ["SF", "PF", "PG"],
    ratings: { scoring: 95, shooting: 76, playmaking: 95, rebounding: 78, perimeterD: 88, interiorD: 70, athleticism: 97, iq: 99 },
    injuryRisk: 30, career: { earlyImpact: 95, aging: 92, winning: 95, elevates: 98, ballDominance: 88, culture: 88, coachability: 85 },
    archetype: "Ageless point-forward" },
  { id: "kawhi", name: "Kawhi Leonard", age: 34, pos: "SF", eligible: ["SF", "PF", "SG"],
    ratings: { scoring: 90, shooting: 84, playmaking: 72, rebounding: 66, perimeterD: 96, interiorD: 66, athleticism: 84, iq: 90 },
    injuryRisk: 78, career: { earlyImpact: 55, aging: 72, winning: 95, elevates: 76, ballDominance: 75, culture: 80, coachability: 82 },
    archetype: "Two-way assassin" },
  { id: "butler", name: "Jimmy Butler", age: 36, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 84, shooting: 72, playmaking: 80, rebounding: 60, perimeterD: 90, interiorD: 58, athleticism: 80, iq: 92 },
    injuryRisk: 48, career: { earlyImpact: 45, aging: 80, winning: 92, elevates: 82, ballDominance: 72, culture: 60, coachability: 78 },
    archetype: "Playoff riser" },
  { id: "pgeorge", name: "Paul George", age: 35, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 86, shooting: 84, playmaking: 76, rebounding: 60, perimeterD: 88, interiorD: 52, athleticism: 84, iq: 86 },
    injuryRisk: 64, career: { earlyImpact: 55, aging: 74, winning: 65, elevates: 76, ballDominance: 72, culture: 82, coachability: 82 },
    archetype: "Two-way wing" },
  { id: "fwagner", name: "Franz Wagner", age: 24, pos: "SF", eligible: ["SF", "PF", "SG"],
    ratings: { scoring: 84, shooting: 76, playmaking: 80, rebounding: 64, perimeterD: 82, interiorD: 54, athleticism: 80, iq: 86 },
    injuryRisk: 30, career: { earlyImpact: 55, aging: 82, winning: 70, elevates: 82, ballDominance: 68, culture: 90, coachability: 88 },
    archetype: "Do-it-all forward" },
  { id: "anunoby", name: "OG Anunoby", age: 28, pos: "SF", eligible: ["SF", "PF", "SG"],
    ratings: { scoring: 74, shooting: 80, playmaking: 56, rebounding: 60, perimeterD: 92, interiorD: 62, athleticism: 84, iq: 80 },
    injuryRisk: 36, career: { earlyImpact: 45, aging: 80, winning: 78, elevates: 70, ballDominance: 35, culture: 88, coachability: 88 },
    archetype: "3-and-D wrecking ball" },
  { id: "mbridges", name: "Mikal Bridges", age: 29, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 78, shooting: 80, playmaking: 64, rebounding: 52, perimeterD: 88, interiorD: 52, athleticism: 82, iq: 82 },
    injuryRisk: 12, career: { earlyImpact: 45, aging: 82, winning: 75, elevates: 72, ballDominance: 45, culture: 92, coachability: 90 },
    archetype: "Iron-man 3-and-D wing" },
  { id: "bingram", name: "Brandon Ingram", age: 28, pos: "SF", eligible: ["SF", "PF", "SG"],
    ratings: { scoring: 85, shooting: 80, playmaking: 76, rebounding: 56, perimeterD: 62, interiorD: 44, athleticism: 76, iq: 82 },
    injuryRisk: 48, career: { earlyImpact: 55, aging: 74, winning: 55, elevates: 72, ballDominance: 80, culture: 78, coachability: 78 },
    archetype: "Smooth shotmaker" },
  { id: "derozan", name: "DeMar DeRozan", age: 36, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 87, shooting: 70, playmaking: 76, rebounding: 52, perimeterD: 56, interiorD: 40, athleticism: 74, iq: 86 },
    injuryRisk: 28, career: { earlyImpact: 60, aging: 78, winning: 58, elevates: 70, ballDominance: 80, culture: 85, coachability: 85 },
    archetype: "Mid-range maestro" },
  { id: "bmiller", name: "Brandon Miller", age: 23, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 82, shooting: 82, playmaking: 66, rebounding: 56, perimeterD: 74, interiorD: 46, athleticism: 82, iq: 78 },
    injuryRisk: 34, career: { earlyImpact: 55, aging: 80, winning: 60, elevates: 72, ballDominance: 72, culture: 85, coachability: 85 },
    archetype: "Scoring wing on the rise" },
  { id: "amen", name: "Amen Thompson", age: 23, pos: "SF", eligible: ["SF", "PG", "SG", "PF"],
    ratings: { scoring: 74, shooting: 56, playmaking: 80, rebounding: 70, perimeterD: 92, interiorD: 58, athleticism: 97, iq: 80 },
    injuryRisk: 26, career: { earlyImpact: 55, aging: 72, winning: 65, elevates: 80, ballDominance: 60, culture: 88, coachability: 86 },
    archetype: "Positionless freak" },
  { id: "jwilliams", name: "Jalen Williams", age: 24, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 84, shooting: 78, playmaking: 78, rebounding: 58, perimeterD: 84, interiorD: 54, athleticism: 84, iq: 86 },
    injuryRisk: 24, career: { earlyImpact: 55, aging: 82, winning: 82, elevates: 82, ballDominance: 62, culture: 90, coachability: 90 },
    archetype: "Two-way connector" },

  // ---------------------------------------------------------------- POWER FORWARDS
  { id: "giannis", name: "Giannis Antetokounmpo", age: 31, pos: "PF", eligible: ["PF", "C", "SF"],
    ratings: { scoring: 95, shooting: 60, playmaking: 80, rebounding: 90, perimeterD: 80, interiorD: 86, athleticism: 97, iq: 86 },
    injuryRisk: 40, career: { earlyImpact: 40, aging: 70, winning: 90, elevates: 82, ballDominance: 80, culture: 88, coachability: 85 },
    archetype: "Two-way force of nature" },
  { id: "paolo", name: "Paolo Banchero", age: 23, pos: "PF", eligible: ["PF", "SF", "C"],
    ratings: { scoring: 87, shooting: 74, playmaking: 78, rebounding: 72, perimeterD: 68, interiorD: 58, athleticism: 82, iq: 82 },
    injuryRisk: 36, career: { earlyImpact: 65, aging: 80, winning: 65, elevates: 78, ballDominance: 80, culture: 85, coachability: 84 },
    archetype: "Bully creator" },
  { id: "scottie", name: "Scottie Barnes", age: 24, pos: "PF", eligible: ["PF", "SF", "C"],
    ratings: { scoring: 78, shooting: 66, playmaking: 82, rebounding: 74, perimeterD: 82, interiorD: 64, athleticism: 86, iq: 84 },
    injuryRisk: 28, career: { earlyImpact: 55, aging: 80, winning: 62, elevates: 86, ballDominance: 65, culture: 90, coachability: 88 },
    archetype: "Point-forward hub" },
  { id: "siakam", name: "Pascal Siakam", age: 31, pos: "PF", eligible: ["PF", "SF", "C"],
    ratings: { scoring: 84, shooting: 76, playmaking: 72, rebounding: 70, perimeterD: 74, interiorD: 60, athleticism: 80, iq: 84 },
    injuryRisk: 22, career: { earlyImpact: 35, aging: 78, winning: 85, elevates: 78, ballDominance: 65, culture: 90, coachability: 90 },
    archetype: "Versatile two-way forward" },
  { id: "markkanen", name: "Lauri Markkanen", age: 28, pos: "PF", eligible: ["PF", "C", "SF"],
    ratings: { scoring: 84, shooting: 86, playmaking: 56, rebounding: 74, perimeterD: 60, interiorD: 56, athleticism: 78, iq: 76 },
    injuryRisk: 32, career: { earlyImpact: 45, aging: 78, winning: 55, elevates: 70, ballDominance: 65, culture: 85, coachability: 85 },
    archetype: "Unicorn stretch four" },
  { id: "jjj", name: "Jaren Jackson Jr.", age: 26, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 80, shooting: 78, playmaking: 50, rebounding: 66, perimeterD: 76, interiorD: 92, athleticism: 82, iq: 78 },
    injuryRisk: 44, career: { earlyImpact: 50, aging: 78, winning: 65, elevates: 72, ballDominance: 55, culture: 88, coachability: 86 },
    archetype: "Stretch rim-protector" },
  { id: "jjohnson", name: "Jalen Johnson", age: 24, pos: "PF", eligible: ["PF", "SF", "C"],
    ratings: { scoring: 78, shooting: 66, playmaking: 76, rebounding: 76, perimeterD: 76, interiorD: 62, athleticism: 90, iq: 78 },
    injuryRisk: 42, career: { earlyImpact: 45, aging: 74, winning: 58, elevates: 80, ballDominance: 60, culture: 85, coachability: 84 },
    archetype: "Transition point-forward" },
  { id: "agordon", name: "Aaron Gordon", age: 30, pos: "PF", eligible: ["PF", "SF", "C"],
    ratings: { scoring: 72, shooting: 72, playmaking: 60, rebounding: 72, perimeterD: 80, interiorD: 68, athleticism: 90, iq: 80 },
    injuryRisk: 34, career: { earlyImpact: 50, aging: 70, winning: 88, elevates: 80, ballDominance: 40, culture: 92, coachability: 90 },
    archetype: "Connective athlete" },
  { id: "draymond", name: "Draymond Green", age: 35, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 58, shooting: 58, playmaking: 88, rebounding: 78, perimeterD: 90, interiorD: 86, athleticism: 76, iq: 97 },
    injuryRisk: 38, career: { earlyImpact: 40, aging: 80, winning: 95, elevates: 95, ballDominance: 40, culture: 55, coachability: 78 },
    archetype: "Defensive QB" },
  { id: "adavis", name: "Anthony Davis", age: 32, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 88, shooting: 66, playmaking: 60, rebounding: 88, perimeterD: 76, interiorD: 96, athleticism: 88, iq: 84 },
    injuryRisk: 70, career: { earlyImpact: 70, aging: 70, winning: 85, elevates: 80, ballDominance: 65, culture: 80, coachability: 82 },
    archetype: "Two-way frontcourt star" },

  // ---------------------------------------------------------------- CENTERS
  { id: "jokic", name: "Nikola Jokić", age: 30, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 95, shooting: 80, playmaking: 99, rebounding: 92, perimeterD: 56, interiorD: 74, athleticism: 58, iq: 99 },
    injuryRisk: 18, career: { earlyImpact: 45, aging: 88, winning: 92, elevates: 99, ballDominance: 80, culture: 92, coachability: 90 },
    archetype: "Point-center fulcrum" },
  { id: "embiid", name: "Joel Embiid", age: 31, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 95, shooting: 78, playmaking: 72, rebounding: 86, perimeterD: 64, interiorD: 92, athleticism: 80, iq: 84 },
    injuryRisk: 82, career: { earlyImpact: 50, aging: 60, winning: 55, elevates: 72, ballDominance: 85, culture: 70, coachability: 75 },
    archetype: "Dominant two-way big" },
  { id: "wemby", name: "Victor Wembanyama", age: 22, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 94, shooting: 82, playmaking: 78, rebounding: 88, perimeterD: 80, interiorD: 99, athleticism: 90, iq: 90 },
    injuryRisk: 40, career: { earlyImpact: 78, aging: 84, winning: 72, elevates: 86, ballDominance: 75, culture: 90, coachability: 88 },
    archetype: "Generational unicorn" },
  { id: "bam", name: "Bam Adebayo", age: 28, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 74, shooting: 60, playmaking: 76, rebounding: 80, perimeterD: 86, interiorD: 84, athleticism: 86, iq: 86 },
    injuryRisk: 20, career: { earlyImpact: 45, aging: 80, winning: 82, elevates: 84, ballDominance: 50, culture: 92, coachability: 92 },
    archetype: "Switch-everything anchor" },
  { id: "kat", name: "Karl-Anthony Towns", age: 30, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 86, shooting: 86, playmaking: 64, rebounding: 86, perimeterD: 54, interiorD: 66, athleticism: 72, iq: 76 },
    injuryRisk: 40, career: { earlyImpact: 65, aging: 78, winning: 60, elevates: 72, ballDominance: 70, culture: 78, coachability: 80 },
    archetype: "Stretch-five scorer" },
  { id: "sabonis", name: "Domantas Sabonis", age: 29, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 80, shooting: 64, playmaking: 84, rebounding: 94, perimeterD: 52, interiorD: 64, athleticism: 64, iq: 88 },
    injuryRisk: 24, career: { earlyImpact: 45, aging: 76, winning: 60, elevates: 86, ballDominance: 60, culture: 88, coachability: 86 },
    archetype: "Hub center / glass cleaner" },
  { id: "chet", name: "Chet Holmgren", age: 23, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 78, shooting: 78, playmaking: 56, rebounding: 76, perimeterD: 70, interiorD: 94, athleticism: 78, iq: 82 },
    injuryRisk: 48, career: { earlyImpact: 60, aging: 82, winning: 80, elevates: 76, ballDominance: 50, culture: 88, coachability: 88 },
    archetype: "Modern stretch-rim five" },
  { id: "mobley", name: "Evan Mobley", age: 24, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 74, shooting: 62, playmaking: 64, rebounding: 80, perimeterD: 80, interiorD: 92, athleticism: 84, iq: 82 },
    injuryRisk: 26, career: { earlyImpact: 50, aging: 82, winning: 68, elevates: 80, ballDominance: 50, culture: 90, coachability: 88 },
    archetype: "DPOY-caliber anchor" },
  { id: "sengun", name: "Alperen Şengün", age: 23, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 82, shooting: 56, playmaking: 86, rebounding: 84, perimeterD: 52, interiorD: 62, athleticism: 62, iq: 88 },
    injuryRisk: 28, career: { earlyImpact: 55, aging: 78, winning: 62, elevates: 86, ballDominance: 70, culture: 85, coachability: 84 },
    archetype: "Playmaking center" },
  { id: "gobert", name: "Rudy Gobert", age: 33, pos: "C", eligible: ["C"],
    ratings: { scoring: 58, shooting: 30, playmaking: 44, rebounding: 92, perimeterD: 56, interiorD: 96, athleticism: 76, iq: 78 },
    injuryRisk: 30, career: { earlyImpact: 35, aging: 72, winning: 65, elevates: 76, ballDominance: 30, culture: 80, coachability: 85 },
    archetype: "Rim-protecting deterrent" },
  { id: "turner", name: "Myles Turner", age: 29, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 68, shooting: 78, playmaking: 44, rebounding: 70, perimeterD: 58, interiorD: 88, athleticism: 74, iq: 78 },
    injuryRisk: 38, career: { earlyImpact: 45, aging: 76, winning: 70, elevates: 70, ballDominance: 45, culture: 85, coachability: 85 },
    archetype: "Stretch-five shot-blocker" },
  { id: "jallen", name: "Jarrett Allen", age: 27, pos: "C", eligible: ["C"],
    ratings: { scoring: 70, shooting: 40, playmaking: 50, rebounding: 86, perimeterD: 54, interiorD: 84, athleticism: 82, iq: 78 },
    injuryRisk: 24, career: { earlyImpact: 45, aging: 78, winning: 68, elevates: 76, ballDominance: 35, culture: 90, coachability: 90 },
    archetype: "Lob-finishing anchor" },
  { id: "kessler", name: "Walker Kessler", age: 24, pos: "C", eligible: ["C"],
    ratings: { scoring: 60, shooting: 30, playmaking: 38, rebounding: 88, perimeterD: 46, interiorD: 92, athleticism: 80, iq: 72 },
    injuryRisk: 22, career: { earlyImpact: 45, aging: 74, winning: 55, elevates: 70, ballDominance: 25, culture: 85, coachability: 85 },
    archetype: "Rim-running shot-blocker" },
  { id: "kporzingis", name: "Kristaps Porziņģis", age: 30, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 84, shooting: 82, playmaking: 50, rebounding: 72, perimeterD: 56, interiorD: 88, athleticism: 66, iq: 78 },
    injuryRisk: 72, career: { earlyImpact: 60, aging: 65, winning: 80, elevates: 70, ballDominance: 60, culture: 80, coachability: 82 },
    archetype: "Stretch-five unicorn" },

  // ================================================================ ALL-TIME GREATS (active 1990+)
  // Rated at career peak; the engine projects each over a normalized 15-year
  // career, so legends rightly sit atop the board.
  { id: "jordan", name: "Michael Jordan", age: 62, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 99, shooting: 84, playmaking: 85, rebounding: 68, perimeterD: 96, interiorD: 55, athleticism: 98, iq: 97 },
    injuryRisk: 16, career: { earlyImpact: 88, aging: 82, winning: 99, elevates: 84, ballDominance: 90, culture: 88, coachability: 88 },
    archetype: "The GOAT" },
  { id: "magic", name: "Magic Johnson", age: 65, pos: "PG", eligible: ["PG", "SF"],
    ratings: { scoring: 86, shooting: 70, playmaking: 99, rebounding: 80, perimeterD: 68, interiorD: 52, athleticism: 84, iq: 99 },
    injuryRisk: 22, career: { earlyImpact: 92, aging: 80, winning: 96, elevates: 99, ballDominance: 88, culture: 92, coachability: 90 },
    archetype: "Showtime maestro" },
  { id: "bird", name: "Larry Bird", age: 68, pos: "SF", eligible: ["SF", "PF"],
    ratings: { scoring: 90, shooting: 92, playmaking: 88, rebounding: 80, perimeterD: 70, interiorD: 50, athleticism: 64, iq: 99 },
    injuryRisk: 42, career: { earlyImpact: 90, aging: 76, winning: 94, elevates: 92, ballDominance: 82, culture: 88, coachability: 88 },
    archetype: "Larry Legend" },
  { id: "hakeem", name: "Hakeem Olajuwon", age: 62, pos: "C", eligible: ["C", "PF"],
    ratings: { scoring: 90, shooting: 55, playmaking: 60, rebounding: 92, perimeterD: 70, interiorD: 99, athleticism: 92, iq: 90 },
    injuryRisk: 24, career: { earlyImpact: 72, aging: 80, winning: 92, elevates: 78, ballDominance: 76, culture: 86, coachability: 86 },
    archetype: "The Dream" },
  { id: "ewing", name: "Patrick Ewing", age: 63, pos: "C", eligible: ["C"],
    ratings: { scoring: 86, shooting: 60, playmaking: 50, rebounding: 88, perimeterD: 58, interiorD: 94, athleticism: 82, iq: 80 },
    injuryRisk: 36, career: { earlyImpact: 72, aging: 70, winning: 70, elevates: 70, ballDominance: 78, culture: 84, coachability: 84 },
    archetype: "Dominant two-way center" },
  { id: "drobinson", name: "David Robinson", age: 60, pos: "C", eligible: ["C"],
    ratings: { scoring: 90, shooting: 55, playmaking: 60, rebounding: 90, perimeterD: 72, interiorD: 97, athleticism: 96, iq: 86 },
    injuryRisk: 32, career: { earlyImpact: 78, aging: 76, winning: 88, elevates: 80, ballDominance: 72, culture: 94, coachability: 92 },
    archetype: "The Admiral" },
  { id: "shaq", name: "Shaquille O'Neal", age: 53, pos: "C", eligible: ["C"],
    ratings: { scoring: 96, shooting: 40, playmaking: 62, rebounding: 92, perimeterD: 56, interiorD: 96, athleticism: 92, iq: 82 },
    injuryRisk: 42, career: { earlyImpact: 84, aging: 66, winning: 92, elevates: 82, ballDominance: 82, culture: 84, coachability: 78 },
    archetype: "Most dominant ever" },
  { id: "duncan", name: "Tim Duncan", age: 49, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 86, shooting: 60, playmaking: 70, rebounding: 92, perimeterD: 72, interiorD: 96, athleticism: 80, iq: 97 },
    injuryRisk: 18, career: { earlyImpact: 85, aging: 88, winning: 95, elevates: 88, ballDominance: 70, culture: 96, coachability: 96 },
    archetype: "The Big Fundamental" },
  { id: "kobe", name: "Kobe Bryant", age: 46, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 97, shooting: 86, playmaking: 80, rebounding: 60, perimeterD: 90, interiorD: 50, athleticism: 94, iq: 94 },
    injuryRisk: 36, career: { earlyImpact: 70, aging: 80, winning: 92, elevates: 76, ballDominance: 92, culture: 80, coachability: 82 },
    archetype: "The Black Mamba" },
  { id: "kg", name: "Kevin Garnett", age: 49, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 86, shooting: 72, playmaking: 76, rebounding: 92, perimeterD: 84, interiorD: 92, athleticism: 88, iq: 92 },
    injuryRisk: 24, career: { earlyImpact: 74, aging: 80, winning: 82, elevates: 88, ballDominance: 72, culture: 82, coachability: 86 },
    archetype: "The Big Ticket" },
  { id: "dirk", name: "Dirk Nowitzki", age: 47, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 92, shooting: 90, playmaking: 62, rebounding: 80, perimeterD: 56, interiorD: 62, athleticism: 70, iq: 90 },
    injuryRisk: 18, career: { earlyImpact: 66, aging: 88, winning: 84, elevates: 78, ballDominance: 78, culture: 92, coachability: 92 },
    archetype: "Original unicorn" },
  { id: "malone", name: "Karl Malone", age: 62, pos: "PF", eligible: ["PF", "C"],
    ratings: { scoring: 92, shooting: 62, playmaking: 64, rebounding: 88, perimeterD: 70, interiorD: 80, athleticism: 90, iq: 84 },
    injuryRisk: 10, career: { earlyImpact: 70, aging: 86, winning: 72, elevates: 76, ballDominance: 78, culture: 82, coachability: 84 },
    archetype: "The Mailman" },
  { id: "barkley", name: "Charles Barkley", age: 62, pos: "PF", eligible: ["PF", "SF"],
    ratings: { scoring: 90, shooting: 68, playmaking: 72, rebounding: 92, perimeterD: 66, interiorD: 72, athleticism: 88, iq: 84 },
    injuryRisk: 30, career: { earlyImpact: 78, aging: 74, winning: 72, elevates: 80, ballDominance: 82, culture: 72, coachability: 76 },
    archetype: "Round Mound of Rebound" },
  { id: "stockton", name: "John Stockton", age: 63, pos: "PG", eligible: ["PG"],
    ratings: { scoring: 72, shooting: 80, playmaking: 99, rebounding: 50, perimeterD: 82, interiorD: 35, athleticism: 70, iq: 96 },
    injuryRisk: 6, career: { earlyImpact: 60, aging: 90, winning: 74, elevates: 95, ballDominance: 78, culture: 90, coachability: 92 },
    archetype: "Assists & steals king" },
  { id: "pippen", name: "Scottie Pippen", age: 60, pos: "SF", eligible: ["SF", "SG", "PF"],
    ratings: { scoring: 80, shooting: 70, playmaking: 82, rebounding: 70, perimeterD: 96, interiorD: 58, athleticism: 90, iq: 90 },
    injuryRisk: 22, career: { earlyImpact: 60, aging: 80, winning: 92, elevates: 88, ballDominance: 60, culture: 82, coachability: 88 },
    archetype: "Ultimate two-way wing" },
  { id: "payton", name: "Gary Payton", age: 57, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 82, shooting: 72, playmaking: 88, rebounding: 56, perimeterD: 98, interiorD: 40, athleticism: 86, iq: 90 },
    injuryRisk: 10, career: { earlyImpact: 62, aging: 84, winning: 78, elevates: 84, ballDominance: 80, culture: 78, coachability: 82 },
    archetype: "The Glove" },
  { id: "drexler", name: "Clyde Drexler", age: 63, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 88, shooting: 74, playmaking: 80, rebounding: 68, perimeterD: 80, interiorD: 48, athleticism: 96, iq: 86 },
    injuryRisk: 22, career: { earlyImpact: 72, aging: 80, winning: 80, elevates: 82, ballDominance: 78, culture: 86, coachability: 86 },
    archetype: "Clyde the Glide" },
  { id: "iverson", name: "Allen Iverson", age: 50, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 93, shooting: 76, playmaking: 80, rebounding: 48, perimeterD: 78, interiorD: 30, athleticism: 96, iq: 82 },
    injuryRisk: 34, career: { earlyImpact: 80, aging: 68, winning: 70, elevates: 74, ballDominance: 95, culture: 72, coachability: 70 },
    archetype: "The Answer" },
  { id: "reggie", name: "Reggie Miller", age: 60, pos: "SG", eligible: ["SG"],
    ratings: { scoring: 84, shooting: 96, playmaking: 60, rebounding: 48, perimeterD: 70, interiorD: 35, athleticism: 72, iq: 86 },
    injuryRisk: 10, career: { earlyImpact: 55, aging: 88, winning: 74, elevates: 72, ballDominance: 70, culture: 86, coachability: 86 },
    archetype: "Clutch sharpshooter" },
  { id: "nash", name: "Steve Nash", age: 51, pos: "PG", eligible: ["PG"],
    ratings: { scoring: 76, shooting: 90, playmaking: 98, rebounding: 48, perimeterD: 50, interiorD: 30, athleticism: 70, iq: 96 },
    injuryRisk: 28, career: { earlyImpact: 55, aging: 88, winning: 76, elevates: 96, ballDominance: 80, culture: 92, coachability: 92 },
    archetype: "Two-time MVP maestro" },
  { id: "kidd", name: "Jason Kidd", age: 52, pos: "PG", eligible: ["PG", "SG"],
    ratings: { scoring: 70, shooting: 66, playmaking: 96, rebounding: 70, perimeterD: 86, interiorD: 40, athleticism: 84, iq: 96 },
    injuryRisk: 16, career: { earlyImpact: 72, aging: 86, winning: 82, elevates: 94, ballDominance: 78, culture: 82, coachability: 86 },
    archetype: "Triple-double point god" },
  { id: "tmac", name: "Tracy McGrady", age: 46, pos: "SF", eligible: ["SG", "SF"],
    ratings: { scoring: 94, shooting: 80, playmaking: 80, rebounding: 66, perimeterD: 76, interiorD: 45, athleticism: 94, iq: 84 },
    injuryRisk: 56, career: { earlyImpact: 72, aging: 62, winning: 60, elevates: 78, ballDominance: 88, culture: 78, coachability: 78 },
    archetype: "Effortless scoring wing" },
  { id: "vince", name: "Vince Carter", age: 48, pos: "SG", eligible: ["SG", "SF"],
    ratings: { scoring: 90, shooting: 82, playmaking: 68, rebounding: 60, perimeterD: 70, interiorD: 42, athleticism: 98, iq: 82 },
    injuryRisk: 22, career: { earlyImpact: 75, aging: 90, winning: 64, elevates: 74, ballDominance: 80, culture: 84, coachability: 84 },
    archetype: "Half-man, half-amazing" },
  { id: "rayallen", name: "Ray Allen", age: 50, pos: "SG", eligible: ["SG"],
    ratings: { scoring: 84, shooting: 97, playmaking: 62, rebounding: 48, perimeterD: 70, interiorD: 35, athleticism: 82, iq: 88 },
    injuryRisk: 12, career: { earlyImpact: 62, aging: 90, winning: 84, elevates: 76, ballDominance: 68, culture: 88, coachability: 90 },
    archetype: "Pure-stroke marksman" },
  { id: "pierce", name: "Paul Pierce", age: 47, pos: "SF", eligible: ["SF", "SG"],
    ratings: { scoring: 88, shooting: 82, playmaking: 70, rebounding: 60, perimeterD: 74, interiorD: 45, athleticism: 76, iq: 88 },
    injuryRisk: 22, career: { earlyImpact: 66, aging: 84, winning: 84, elevates: 76, ballDominance: 80, culture: 82, coachability: 84 },
    archetype: "The Truth" },
  { id: "wade", name: "Dwyane Wade", age: 43, pos: "SG", eligible: ["SG", "PG"],
    ratings: { scoring: 92, shooting: 70, playmaking: 82, rebounding: 56, perimeterD: 84, interiorD: 52, athleticism: 94, iq: 88 },
    injuryRisk: 46, career: { earlyImpact: 78, aging: 72, winning: 88, elevates: 82, ballDominance: 86, culture: 86, coachability: 86 },
    archetype: "Flash" },
  { id: "melo", name: "Carmelo Anthony", age: 41, pos: "SF", eligible: ["SF", "PF"],
    ratings: { scoring: 92, shooting: 80, playmaking: 62, rebounding: 64, perimeterD: 56, interiorD: 45, athleticism: 82, iq: 80 },
    injuryRisk: 22, career: { earlyImpact: 78, aging: 80, winning: 62, elevates: 66, ballDominance: 88, culture: 78, coachability: 76 },
    archetype: "Pure scorer" },
  { id: "dwight", name: "Dwight Howard", age: 39, pos: "C", eligible: ["C"],
    ratings: { scoring: 76, shooting: 30, playmaking: 50, rebounding: 96, perimeterD: 60, interiorD: 96, athleticism: 96, iq: 72 },
    injuryRisk: 38, career: { earlyImpact: 80, aging: 70, winning: 76, elevates: 76, ballDominance: 55, culture: 66, coachability: 70 },
    archetype: "Superman" },
  { id: "granthill", name: "Grant Hill", age: 53, pos: "SF", eligible: ["SF", "SG"],
    ratings: { scoring: 86, shooting: 70, playmaking: 84, rebounding: 68, perimeterD: 78, interiorD: 48, athleticism: 92, iq: 88 },
    injuryRisk: 52, career: { earlyImpact: 85, aging: 78, winning: 66, elevates: 86, ballDominance: 80, culture: 90, coachability: 90 },
    archetype: "Do-it-all forward" },
  { id: "zo", name: "Alonzo Mourning", age: 55, pos: "C", eligible: ["C"],
    ratings: { scoring: 82, shooting: 50, playmaking: 45, rebounding: 84, perimeterD: 56, interiorD: 95, athleticism: 86, iq: 78 },
    injuryRisk: 48, career: { earlyImpact: 72, aging: 66, winning: 74, elevates: 70, ballDominance: 70, culture: 82, coachability: 82 },
    archetype: "Relentless rim protector" },
  { id: "mutombo", name: "Dikembe Mutombo", age: 59, pos: "C", eligible: ["C"],
    ratings: { scoring: 60, shooting: 30, playmaking: 38, rebounding: 92, perimeterD: 50, interiorD: 98, athleticism: 80, iq: 78 },
    injuryRisk: 22, career: { earlyImpact: 60, aging: 82, winning: 70, elevates: 74, ballDominance: 35, culture: 88, coachability: 88 },
    archetype: "Finger-wag deterrent" },
];

// ----------------------------------------------------------------------------
//  Derived advanced attributes: clutch, steals, blocks, interiorLoad
//
//  These power the steals/blocks/shutdown-defense, clutch, and roster-construction
//  (paint-clog / usage) modeling. Most are derived from the core profile; the
//  OVERRIDES table pins values for players whose real-life profile the
//  derivation can't capture (elite ball-hawks, shot-blockers, clutch closers,
//  paint-bound bigs).
// ----------------------------------------------------------------------------
(function augmentPlayers() {
  const clamp = (x, lo, hi) => Math.max(lo, Math.min(hi, x));

  const OVERRIDES = {
    // --- defense: steals / blocks / shutdown + paint load ---
    ddaniels: { steals: 99, blocks: 32 },
    amen: { steals: 88, blocks: 55 },
    anunoby: { steals: 72, blocks: 52 },
    mbridges: { steals: 72, blocks: 46 },
    kawhi: { steals: 82, blocks: 46, clutch: 92 },
    dwhite: { steals: 70, blocks: 64, clutch: 80 },
    bam: { steals: 68, blocks: 72, interiorLoad: 60 },
    draymond: { steals: 72, blocks: 72, interiorLoad: 50 },
    giannis: { steals: 70, blocks: 78, interiorLoad: 92, clutch: 84 },
    gobert: { steals: 38, blocks: 98, interiorLoad: 88, clutch: 50 },
    wemby: { steals: 60, blocks: 99, interiorLoad: 58, clutch: 80 },
    mobley: { steals: 50, blocks: 92, interiorLoad: 70 },
    chet: { steals: 46, blocks: 94, interiorLoad: 52 },
    jjj: { steals: 55, blocks: 94, interiorLoad: 56 },
    turner: { steals: 38, blocks: 90, interiorLoad: 44 },
    kessler: { steals: 30, blocks: 95, interiorLoad: 88, clutch: 52 },
    jallen: { steals: 35, blocks: 82, interiorLoad: 85, clutch: 58 },
    embiid: { steals: 45, blocks: 88, interiorLoad: 82, clutch: 78 },
    adavis: { steals: 55, blocks: 92, interiorLoad: 76, clutch: 80 },
    agordon: { steals: 52, blocks: 60, interiorLoad: 60 },
    sabonis: { steals: 45, blocks: 44, interiorLoad: 86, clutch: 60 },
    sengun: { steals: 48, blocks: 50, interiorLoad: 82 },
    jokic: { steals: 60, blocks: 55, interiorLoad: 66, clutch: 90 },
    kat: { steals: 40, blocks: 58, interiorLoad: 55 },
    markkanen: { interiorLoad: 40 },
    paolo: { interiorLoad: 64, clutch: 78 },
    jjohnson: { interiorLoad: 60, steals: 58 },
    siakam: { interiorLoad: 58, steals: 55 },
    // --- clutch closers (and notable non-clutch) ---
    dlillard: { clutch: 97 },
    kyrie: { clutch: 95 },
    curry: { clutch: 93, steals: 60 },
    lebron: { clutch: 90, steals: 60, blocks: 55 },
    durant: { clutch: 92, blocks: 60 },
    sga: { clutch: 90, steals: 78 },
    tatum: { clutch: 85, steals: 55 },
    butler: { clutch: 92, steals: 78 },
    jbrown: { clutch: 84, steals: 60 },
    brunson: { clutch: 90 },
    booker: { clutch: 88 },
    mitchell: { clutch: 84 },
    edwards: { clutch: 86, steals: 60 },
    murray: { clutch: 92 },
    derozan: { clutch: 86 },
    trae: { clutch: 82 },
    halliburton: { clutch: 84, steals: 62 },
    reaves: { clutch: 80 },
    maxey: { clutch: 80, steals: 55 },
    herro: { clutch: 78 },
    klay: { clutch: 88, steals: 55 },
    cp3: { clutch: 80, steals: 82 },
    harden: { clutch: 52, steals: 60 },
    westbrook: { clutch: 50, steals: 72 },
    bane: { clutch: 78 },
    pgeorge: { steals: 70, clutch: 76 },
    fwagner: { steals: 58, clutch: 76 },
    jwilliams: { steals: 62, clutch: 78 },
    lavine: { clutch: 60 },
    // --- all-time greats ---
    jordan: { clutch: 99, steals: 92, blocks: 45, interiorLoad: 28 },
    magic: { clutch: 90, steals: 78, blocks: 30, interiorLoad: 32 },
    bird: { clutch: 97, steals: 80, blocks: 40, interiorLoad: 30 },
    hakeem: { clutch: 90, steals: 82, blocks: 99, interiorLoad: 80 },
    ewing: { clutch: 78, steals: 45, blocks: 92, interiorLoad: 82 },
    drobinson: { clutch: 80, steals: 80, blocks: 96, interiorLoad: 70 },
    shaq: { clutch: 84, steals: 45, blocks: 88, interiorLoad: 94 },
    duncan: { clutch: 88, steals: 60, blocks: 90, interiorLoad: 78 },
    kobe: { clutch: 98, steals: 82, blocks: 40, interiorLoad: 26 },
    kg: { clutch: 82, steals: 80, blocks: 86, interiorLoad: 64 },
    dirk: { clutch: 95, steals: 50, blocks: 60, interiorLoad: 44 },
    malone: { clutch: 78, steals: 72, blocks: 60, interiorLoad: 76 },
    barkley: { clutch: 82, steals: 72, blocks: 50, interiorLoad: 72 },
    stockton: { clutch: 84, steals: 96, blocks: 18, interiorLoad: 12 },
    pippen: { clutch: 82, steals: 94, blocks: 55, interiorLoad: 25 },
    payton: { clutch: 84, steals: 95, blocks: 28, interiorLoad: 20 },
    drexler: { clutch: 84, steals: 88, blocks: 55, interiorLoad: 26 },
    iverson: { clutch: 90, steals: 94, blocks: 18, interiorLoad: 18 },
    reggie: { clutch: 97, steals: 64, blocks: 20, interiorLoad: 12 },
    nash: { clutch: 86, steals: 48, blocks: 14, interiorLoad: 12 },
    kidd: { clutch: 80, steals: 90, blocks: 24, interiorLoad: 14 },
    tmac: { clutch: 86, steals: 76, blocks: 56, interiorLoad: 26 },
    vince: { clutch: 82, steals: 70, blocks: 56, interiorLoad: 24 },
    rayallen: { clutch: 96, steals: 62, blocks: 22, interiorLoad: 12 },
    pierce: { clutch: 93, steals: 70, blocks: 28, interiorLoad: 26 },
    wade: { clutch: 92, steals: 86, blocks: 72, interiorLoad: 30 },
    melo: { clutch: 86, steals: 55, blocks: 34, interiorLoad: 42 },
    dwight: { clutch: 64, steals: 56, blocks: 95, interiorLoad: 88 },
    granthill: { clutch: 80, steals: 76, blocks: 46, interiorLoad: 26 },
    zo: { clutch: 76, steals: 46, blocks: 96, interiorLoad: 82 },
    mutombo: { clutch: 60, steals: 46, blocks: 99, interiorLoad: 82 },
  };

  // Scoring efficiency (true-shooting, higher = better) and turnover-proneness
  // (higher = worse). Inefficient, turnover-heavy volume scorers get docked;
  // efficient, careful creators get a boost. Unlisted players default to neutral.
  const EFFTOV = {
    curry: { efficiency: 91, turnovers: 36 }, jokic: { efficiency: 92, turnovers: 42 },
    durant: { efficiency: 90, turnovers: 34 }, sga: { efficiency: 86, turnovers: 38 },
    lebron: { efficiency: 84, turnovers: 46 }, cp3: { efficiency: 82, turnovers: 14 },
    kyrie: { efficiency: 84, turnovers: 38 }, mbridges: { efficiency: 82, turnovers: 24 },
    klay: { efficiency: 86, turnovers: 22 }, dwhite: { efficiency: 80, turnovers: 30 },
    bane: { efficiency: 83, turnovers: 30 }, reaves: { efficiency: 81, turnovers: 34 },
    brunson: { efficiency: 80, turnovers: 32 }, tatum: { efficiency: 80, turnovers: 40 },
    jbrown: { efficiency: 77, turnovers: 46 }, booker: { efficiency: 81, turnovers: 38 },
    bam: { efficiency: 80, turnovers: 38 }, wemby: { efficiency: 80, turnovers: 46 },
    mobley: { efficiency: 79, turnovers: 32 }, chet: { efficiency: 81, turnovers: 34 },
    kat: { efficiency: 83, turnovers: 44 }, markkanen: { efficiency: 82, turnovers: 28 },
    sabonis: { efficiency: 84, turnovers: 50 }, gobert: { efficiency: 88, turnovers: 40 },
    jallen: { efficiency: 86, turnovers: 34 }, kessler: { efficiency: 86, turnovers: 30 },
    agordon: { efficiency: 82, turnovers: 32 }, maxey: { efficiency: 78, turnovers: 36 },
    halliburton: { efficiency: 82, turnovers: 28 }, edwards: { efficiency: 78, turnovers: 44 },
    dlillard: { efficiency: 80, turnovers: 40 }, giannis: { efficiency: 84, turnovers: 58 },
    jwilliams: { efficiency: 79, turnovers: 38 }, siakam: { efficiency: 78, turnovers: 36 },
    mitchell: { efficiency: 76, turnovers: 44 }, derozan: { efficiency: 74, turnovers: 36 },
    anunoby: { efficiency: 78, turnovers: 26 }, jjj: { efficiency: 76, turnovers: 36 },
    paolo: { efficiency: 70, turnovers: 56 }, cade: { efficiency: 71, turnovers: 60 },
    sengun: { efficiency: 76, turnovers: 60 }, embiid: { efficiency: 82, turnovers: 52 },
    adavis: { efficiency: 82, turnovers: 42 }, scottie: { efficiency: 72, turnovers: 48 },
    // inefficient / turnover-prone volume scorers
    trae: { efficiency: 60, turnovers: 72 }, lamelo: { efficiency: 60, turnovers: 74 },
    westbrook: { efficiency: 52, turnovers: 80 }, harden: { efficiency: 68, turnovers: 66 },
    luka: { efficiency: 76, turnovers: 66 }, lavine: { efficiency: 74, turnovers: 40 },
    herro: { efficiency: 70, turnovers: 42 }, fox: { efficiency: 70, turnovers: 50 },
    bingram: { efficiency: 70, turnovers: 44 }, garland: { efficiency: 74, turnovers: 46 },
    mcollum: { efficiency: 74, turnovers: 34 }, bmiller: { efficiency: 71, turnovers: 44 },
    pgeorge: { efficiency: 76, turnovers: 40 }, fwagner: { efficiency: 74, turnovers: 44 },
    murray: { efficiency: 78, turnovers: 36 }, jjohnson: { efficiency: 72, turnovers: 48 },
    amen: { efficiency: 68, turnovers: 50 }, ddaniels: { efficiency: 70, turnovers: 36 },
    turner: { efficiency: 80, turnovers: 28 }, kawhi: { efficiency: 82, turnovers: 30 },
    butler: { efficiency: 82, turnovers: 38 },
    // --- all-time greats ---
    jordan: { efficiency: 86, turnovers: 38 }, magic: { efficiency: 90, turnovers: 44 },
    bird: { efficiency: 86, turnovers: 40 }, hakeem: { efficiency: 80, turnovers: 42 },
    ewing: { efficiency: 76, turnovers: 44 }, drobinson: { efficiency: 84, turnovers: 42 },
    shaq: { efficiency: 88, turnovers: 50 }, duncan: { efficiency: 86, turnovers: 38 },
    kobe: { efficiency: 80, turnovers: 42 }, kg: { efficiency: 84, turnovers: 40 },
    dirk: { efficiency: 88, turnovers: 36 }, malone: { efficiency: 82, turnovers: 44 },
    barkley: { efficiency: 86, turnovers: 48 }, stockton: { efficiency: 90, turnovers: 24 },
    pippen: { efficiency: 80, turnovers: 40 }, payton: { efficiency: 80, turnovers: 40 },
    drexler: { efficiency: 82, turnovers: 40 }, iverson: { efficiency: 68, turnovers: 46 },
    reggie: { efficiency: 88, turnovers: 30 }, nash: { efficiency: 92, turnovers: 40 },
    kidd: { efficiency: 74, turnovers: 42 }, tmac: { efficiency: 78, turnovers: 44 },
    vince: { efficiency: 80, turnovers: 38 }, rayallen: { efficiency: 90, turnovers: 30 },
    pierce: { efficiency: 82, turnovers: 40 }, wade: { efficiency: 80, turnovers: 46 },
    melo: { efficiency: 76, turnovers: 38 }, dwight: { efficiency: 86, turnovers: 46 },
    granthill: { efficiency: 82, turnovers: 42 }, zo: { efficiency: 80, turnovers: 44 },
    mutombo: { efficiency: 80, turnovers: 40 },
  };

  PLAYER_POOL.forEach((p) => {
    const r = p.ratings;
    const c = p.career;
    const guard = p.pos === "PG" || p.pos === "SG";
    const big = p.pos === "C" || p.pos === "PF";
    const derived = {
      // blocks track rim protection; guards rarely block shots
      blocks: clamp(Math.round(r.interiorD - (guard ? 20 : 0) + (r.athleticism - 75) * 0.2), 5, 99),
      // steals track perimeter disruption (hands, anticipation, athleticism)
      steals: clamp(Math.round(r.perimeterD * 0.5 + r.athleticism * 0.15 + r.iq * 0.12 - 6), 8, 90),
      // clutch leans on winning pedigree + shot-making + feel
      clutch: clamp(Math.round(c.winning * 0.45 + r.scoring * 0.3 + r.iq * 0.1 + 6), 25, 97),
      // interiorLoad = how much offense comes from the paint/post (overlap risk)
      interiorLoad: big
        ? clamp(Math.round(r.interiorD * 0.32 + r.rebounding * 0.3 + (100 - r.shooting) * 0.26 - 14), 8, 95)
        : clamp(Math.round(r.scoring * 0.12 + (100 - r.shooting) * 0.1), 5, 45),
      // efficiency = scoring/true-shooting efficiency (default neutral)
      efficiency: 70,
      // turnovers = turnover-proneness, higher is worse (default neutral)
      turnovers: 42,
    };
    p.ext = Object.assign(derived, OVERRIDES[p.id] || {}, EFFTOV[p.id] || {});
  });

  // Official NBA headshots (public CDN). Players without an id fall back to an
  // initials avatar in the UI, so a wrong/missing id never shows a broken image.
  const NBA_IDS = {
    sga: 1628983, luka: 1629029, curry: 201939, halliburton: 1630169, brunson: 1628973,
    cade: 1630595, lamelo: 1630163, maxey: 1630178, fox: 1628368, trae: 1629027,
    garland: 1629636, murray: 1627750, dlillard: 203081, ddaniels: 1641725, cp3: 101108,
    westbrook: 201566, kyrie: 202681,
    edwards: 1630162, booker: 1626164, mitchell: 1628378, jbrown: 1627759, klay: 202691,
    harden: 201935, bane: 1630217, reaves: 1630559, dwhite: 1628401, lavine: 203897,
    herro: 1629639, mcollum: 203468,
    tatum: 1628369, durant: 201142, lebron: 2544, kawhi: 202695, butler: 202710,
    pgeorge: 202331, fwagner: 1630532, anunoby: 1628384, mbridges: 1628969, bingram: 1627742,
    derozan: 201942, bmiller: 1641706, amen: 1641708, jwilliams: 1631114,
    giannis: 203507, paolo: 1631094, scottie: 1630567, siakam: 1627783, markkanen: 1628374,
    jjj: 1628991, jjohnson: 1630552, agordon: 203932, draymond: 203110, adavis: 203076,
    jokic: 203999, embiid: 203954, wemby: 1641705, bam: 1628389, kat: 1626157,
    sabonis: 1627734, chet: 1631096, mobley: 1630596, sengun: 1630578, gobert: 203497,
    turner: 1626167, jallen: 1628386, kessler: 1631117, kporzingis: 204001,
    // all-time greats
    jordan: 893, magic: 77142, bird: 1449, hakeem: 165, ewing: 121, drobinson: 764,
    shaq: 406, duncan: 1495, kobe: 977, kg: 708, dirk: 1717, malone: 252, barkley: 787,
    stockton: 304, pippen: 547, payton: 56, drexler: 200, iverson: 947, reggie: 397,
    nash: 959, kidd: 429, tmac: 1503, vince: 1713, rayallen: 951, pierce: 1718,
    wade: 2548, melo: 2546, dwight: 2730, granthill: 701, zo: 296, mutombo: 209,
  };
  PLAYER_POOL.forEach((p) => {
    if (NBA_IDS[p.id]) {
      p.photo = "https://cdn.nba.com/headshots/nba/latest/260x190/" + NBA_IDS[p.id] + ".png";
    }
    // Initials shown when there's no photo (or it fails to load).
    p.initials = p.name.split(" ").map((w) => w[0]).filter(Boolean).slice(0, 2).join("").toUpperCase();
  });
})();

// Make available both as a module export and on the global scope (browser).
if (typeof module !== "undefined" && module.exports) {
  module.exports = { PLAYER_POOL };
}
if (typeof window !== "undefined") {
  window.PLAYER_POOL = PLAYER_POOL;
}
